[build]
  command = "cd client && npm run build"
  publish = "client/build"
  functions = "netlify-functions/functions"

[dev]
  functions = "netlify-functions/functions"
  publish = "client/build"

[functions]
  directory = "netlify-functions/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
