[build]
  command = "npm install --prefix client && npm run build --prefix client"
  publish = "client/build"
  functions = "netlify-functions/functions"

[dev]
  functions = "netlify-functions/functions"
  publish = "client/build"
  targetPort = 3000

[functions]
  directory = "netlify-functions/functions"


